#!/bin/bash

cs="/srv/git/java/"
export PATH=$cs:$PATH
cd $cs
exec bash

#http://stackoverflow.com/questions/14637979/how-to-permanently-set-path-on-linux
#http://stackoverflow.com/questions/1158091/defining-a-variable-with-or-without-export
#http://superuser.com/questions/448775/how-do-i-create-a-program-shortcut-for-a-command-in-ubuntu-12-04-lts
#http://stackoverflow.com/questions/3512055/avoid-gnome-terminal-close-after-script-execution
